# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.cache/wt [current_project]
set_property parent.project_path C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/letter_rom.v
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/display_rom.v
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/spike_rom.v
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/vga_sync.v
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/Seg_7_Display.v
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/ps2_rx.v
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/clk_50m_generator.v
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/self_anim.v
  C:/Users/Roger/Documents/Homework/ECE415/self_proj/self_proj.srcs/sources_1/new/self_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Roger/Documents/Homework/ECE415/self_proj/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Roger/Documents/Homework/ECE415/self_proj/Nexys4DDR_Master.xdc]


synth_design -top self_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef self_top.dcp

catch { report_utilization -file self_top_utilization_synth.rpt -pb self_top_utilization_synth.pb }
